### ISSUE TITLE
Error Number 69

### ISSUE THREAD

**Issue by HaythamQuake** [Raytwo/Cobalt#1]
Tried using the latest version of Cobalt to test out DC's BOaMO update but came across this odd error that prevents me from starting the game. Since the error said to show it to the developer, I thought I'd send it here.

![image](https://github.com/Raytwo/Cobalt/assets/80391589/93440fe9-6e1e-4f6b-b8c7-13cd5c7b6508)

**Comment by Raytwo** [comment]
Hey there, seems like you forgot to remove your shop.xml.bundle in your romfs.

**Comment by HaythamQuake** [comment]
Hello and thank you for your response, I have realized that it is conflicting with another mod that I have that is currently not Cobalt compatible. I didn't realize cross-compatibility would be an issue so I shall either wait for the mod creator to make their mod compatible with Cobalt or just disable Cobalt in the meantime. Thank you again and amazing work to you and the rest of the team who assisted making this tool.
