### ISSUE TITLE
Cobalt error

### ISSUE THREAD

**Issue by mbmcake** [Raytwo/Cobalt#10]
Cobalt is now panicking and I don't know why

![image](https://github.com/Raytwo/Cobalt/assets/75872627/19eb5a77-16fd-408d-a81d-61db8ae146b9)

**Comment by DogeThis** [comment]
This issue was fixed by migrating the mod to be Cobalt-compatible: https://ptb.discord.com/channels/608790115002875934/1065367882290176060/1128887211706830868
