### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by MCmcy** [Raytwo/Cobalt#11]
whe I use v0.17 ，in 邪龙之章6 Phase star ，the game report an error and exit。when I use version0.9 it looks like working fine

**Comment by DogeThis** [comment]
@MCmcy Can you include a save file and your zipped directory of loaded mods

**Comment by chrom-sevy** [comment]
@MCmcy can you please show the error here

**Comment by Raytwo** [comment]
Going to close this due to the lack of response, feel free to re-open an issue if the issue still exists.
