### ISSUE TITLE
Crash with clean install

### ISSUE THREAD

**Issue by whnds** [Raytwo/Cobalt#17]
I run into this issue on a clean install of Cobalt with no mods. The folders are set up according to the installation instructions.
![Capture](https://github.com/Raytwo/Cobalt/assets/109813386/f12faff5-bb99-4c4f-8303-1028e0b951cb)

**Comment by Raytwo** [comment]
At what point during boot is this happening? Also please send your latest crash log after this happens.

**Comment by Raytwo** [comment]
Fixed, please download the latest release!
