### ISSUE TITLE
Cobalt not installing correctly.

### ISSUE THREAD

**Issue by Pikrioling** [Raytwo/Cobalt#19]
So, I want to install Cobalt on a Vanilla game of Engage on Ryujinx. 
I follow the intstructions reported here, and nothing happens.
I talk with a friend, and they tell me the path that Cobalt should be installed in like this:
"so you should have this C:\Users\[your name ]\AppData\Roaming\Ryujinx\mods\contents\0100a6301214e000\skyline\exefs
and in exefs there should be main.npdm and subsdk9"
I do that, and now Cobalt gives me this error message: 
![Immagine 2023-07-27 143337](https://github.com/Raytwo/Cobalt/assets/86151968/cdf7f6a6-b162-4bd6-b658-6c223acef117)
At least it's an improvement...
What do I do?

**Comment by Pikrioling** [comment]
![Immagine 2023-07-27 180750](https://github.com/Raytwo/Cobalt/assets/86151968/4acb75a0-874d-4f41-ba5e-a3b8500787da)
Now what?

**Comment by Raytwo** [comment]
At what point during boot is this happening? Also please send your latest crash log after this happens.

**Comment by Pikrioling** [comment]
When the game starts loading. It loads for a while and then shows me this. It also doesn't crash, I have to manually stop the emulation myself (unless it takes a while to close by itself.)
Here is the latest Log I have. Not sure if it is a crash one.
[Ryujinx_1.1.969_2023-07-27_18-42-04.log](https://github.com/Raytwo/Cobalt/files/12187840/Ryujinx_1.1.969_2023-07-27_18-42-04.log)

**Comment by Raytwo** [comment]
One more question: Did you have a savefile before booting the game? I can't manage to reproduce this so it's difficult to address.

**Comment by Pikrioling** [comment]
Yes I did have a savefile, here:
[Engage Saves.zip](https://github.com/Raytwo/Cobalt/files/12207331/Engage.Saves.zip)
As for the prior versions, I haven't updated anything after I started trying to install Cobalt (well except for like the Heroes Bonuses update)
Here's an info dump: my computer is pretty weak, so maybe Cobalt sees the game taking a long time to load and thinks something went wrong?
I also tried installing Boamo before moving the Cobalt files to the location where it makes Cobalt start existing, but I replaced those files and moved out the Boamo files.

**Comment by Raytwo** [comment]
> As for the prior versions, I haven't updated anything after I started trying to install Cobalt (well except for like the Heroes Bonuses update)

I mean like, does this happen on Cobalt 0.19.0 for example?

**Comment by Pikrioling** [comment]
I haven't checked yet. Will get back to you.

**Comment by Raytwo** [comment]
That's right

**Comment by Pikrioling** [comment]
I was worried that sd: was like C:

**Comment by Raytwo** [comment]
Here's how it should look:
![image](https://github.com/Raytwo/Cobalt/assets/18125485/5f3eca61-7221-4a76-b274-82cbaf065a52)

![image](https://github.com/Raytwo/Cobalt/assets/18125485/f73101c9-3500-4dcd-a9e0-80dc15cec8cd)

**Comment by Pikrioling** [comment]
That's how it is for me (excluding the non highlighted files.)
subsdk9 doesn't have the same icon for me and is just a file with no extension and also is a lot bigger in size.

**Comment by Pikrioling** [comment]
Alright tested it with Version v0.22.0 and it's basically the same. Here's the error message:
![Immagine 2023-07-29 165943](https://github.com/Raytwo/Cobalt/assets/86151968/b8574567-0e5f-4e1e-ba0c-bd14b232e4e8)

**Comment by Raytwo** [comment]
> subsdk9 doesn't have the same icon for me and is just a file with no extension and also is a lot bigger in size.

Yeah that's normal, this is just a trick for development purposes. ;p

I am really confused about your error though. May I ask what language you play in?

**Comment by Pikrioling** [comment]
English. I have "played" the game for about 2 hours, but never saved.

**Comment by Raytwo** [comment]
I am so confused right now.

**Comment by Raytwo** [comment]
Ok I managed to replicate it and no you did not have a save on the emulator before starting lol.
I'll address this.

**Comment by Pikrioling** [comment]
When you asked me when I had a save you meant for the first time I booted the game? Because I interpreted it as the first time I booted it with Cobalt.

**Comment by Raytwo** [comment]
There you go, please download the latest release!

**Comment by Pikrioling** [comment]
![Immagine 2023-07-29 174352](https://github.com/Raytwo/Cobalt/assets/86151968/b0bdace4-c23e-4904-8719-ef3f00ea4890)
YES
