### ISSUE TITLE
[Panic] Cobalt Panic when Changing Language or Voice Language

### ISSUE THREAD

**Issue by Zizou-DW** [Raytwo/Cobalt#20]
### System Firmware Version

16.0.3

### Atmosphere Version

AMS 1.5.4|S / Atmosphere 1.5.4

### Cobalt Version

0.23.0

### Steps to reproduce

Simply open Engage, and wait for it to reach the Title screen. Open options, Change Language, and then either modify the Language the game is currently using, or change the Language all of the Voices are in.

### Details

![2023080122310600-1AB131B6E6571375B79964211BB3F5AE](https://github.com/Raytwo/Cobalt/assets/141268543/cd3d8175-2d78-4ef4-b4c0-2ed213543ee7)
The same error occurs for both language and voice language.

### Minimal modpack to reproduce the panic

_Highly unlikely that it's linked to a modpack, but I am just running Battle Outfits and Playable Bosses._

**Comment by Raytwo** [comment]
Addressed with Cobalt v0.23.1
