### ISSUE TITLE
Crashing when three asset tables are present

### ISSUE THREAD

**Issue by derek56767** [Raytwo/Cobalt#21]
### System Firmware Version

Ryujinx 1.1.972

### Atmosphere Version

Ryujinx

### Cobalt Version

0.23.0

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [x] After the Switch boot animation
- [ ] While the picture is displayed on boot
- [ ] While the spinner is displayed on boot
- [ ] At random
- [ ] After a long time playing

### Details

If three or more mods containing assettable are installed in version 0.23, the game crashes upon entering the Somniel if any characters are currently equipped with an outfit added from the mods. If no characters are wearing these outfits, then entering the boutique will cause the console to say that  MapPhysicalMemory( ) = LimitReached on multiple lines, with a subsequent crash. In some cases, there is no immediate crash, but if the MapPhysicalMemory( ) = LimitReached message shows up more than once in the console, the game will crash soon. 

There are no problems with merging in version 0.22, even with four assettables. 

Tested with the following combinations of mods:
- [Reverse Recruitment](https://gamebanana.com/mods/426933) + BOAMO  +  [Minecraft Steve Head Accessory](https://gamebanana.com/mods/453592) (note: Steve Head accessory's assettable is only a single line added to the base game's)
- [Reverse Recruitment](https://gamebanana.com/mods/426933) + BOAMO  +   [New Outfits (Cobalt)](https://gamebanana.com/mods/450317) 
- [Anybody BUT Alear](https://gamebanana.com/mods/456914) + [Emblem Classes and More](https://gamebanana.com/mods/439897) crashes after entering boutique and scrolling through the outfits for a while
- [Anybody BUT Alear](https://gamebanana.com/mods/456914) + [Emblem Classes and More](https://gamebanana.com/mods/439897) + [New Outfits (Cobalt)](https://gamebanana.com/mods/450317) crashes almost immediately
- Also said to happen with [Anybody BUT Alear](https://gamebanana.com/mods/456914) + BOAMO + [Oersted's Playable Bosses](https://gamebanana.com/mods/424935), but I did not test this myself.
- Does not seem to occur for BOAMO + New Outfits  + Steve Head Accessory, however. Perhaps one of the mods must have directly replaced lines in the assettable (as is the case for Reverse Recruitment and Anyone BUT Alear)

Note: 
- only having two assettables might still cause the MapPhysicalMemory( ) = LimitReached message to show up once, but the game still seemed to be playable. This occurred with Reverse Recruitment + BOAMO. 
- with four assettables, the game gets dark, grayscale, fuzzy, and laggy before crashing after moving the camera or Alear enough. I think this occurred with Reverse Recruitment + Emblem Classes + New Outfits + Steve Head Accessory.
- Assettable size comparison: Emblem Classes (8.88 MB) > Anyone BUT Alear (5.67 MB) > New Outfits, Reverse Recruitment (4.9 MB) > Steve Head/Base game (4.87 MB) I have a feeling size of assettable or number of lines added is also a factor because having the largest two installed and then entering the boutique resulted in an imminent crash.
- Version of Emblem Classes used in these cases is a little bit larger than the current release (I am the creator) on GameBanana but I don't think this should affect replicability in any way.

### Crash report

```shell
(After loading the bundles under the Data folder)

00:01:57.047 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Label #0: MID_SYS_Mode_Phoenix

00:01:57.047 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: After text #0

00:01:57.048 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: Label #1: MID_H_Mode_Phoenix

00:01:57.048 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: After text #1

00:02:07.386 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:02:07.386 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:02:08.169 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:02:17.711 |S| HLE.OsThread.22 ServicePctl IsFreeCommunicationAvailable: Stubbed. 
00:02:21.277 |W| HLE.GuestThread.21 KernelSvc OutputDebugString: ScriptSystem::Log: Startup

00:02:37.964 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:02:38.968 |E| HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 4721 took more than 1000ms, resuming execution...
00:02:53.920 |W| HLE.GuestThread.26 KernelSvc : MapPhysicalMemory() = LimitReached
00:02:58.712 |W| HLE.GuestThread.48 KernelSvc : MapPhysicalMemory() = LimitReached
00:02:58.712 |W| HLE.GuestThread.48 KernelSvc : MapPhysicalMemory() = LimitReached
00:02:58.830 |W| HLE.GuestThread.49 KernelSvc : MapPhysicalMemory() = LimitReached
00:02:59.190 |I| HLE.GuestThread.49 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Fire Emblem Engage, PID: 98
   0x00000000089a8950	main:0x9a4950	
   0x00000000089ad58c	main:0x9a958c	
   0x000000000866de0c	main:0x669e0c	
   0x000000000866547c	main:0x66147c	
   0x0000000008664e0c	main:0x660e0c	
   0x000000000866435c	main:0x66035c	
   0x000000000865dd78	main:0x659d78	
   0x000000000865dc6c	main:0x659c6c	
   0x000000000865c780	main:0x658780	
   0x00000000086553b4	main:0x6513b4	
   0x000000000866dd14	main:0x669d14	
   0x00000000088eb938	main:0x8e7938	
   0x0000000008c32d34	main:0xc2ed34	
   0x000000000871c798	main:0x718798	
   0x00000000085370e0	main:0x5330e0	
   0x0000000008537040	main:0x533040	
   0x0000000008545018	main:0x541018	
   0x0000000008c414a8	main:0xc3d4a8	
   0x000000000872a3ec	main:0x7263ec	
   0x000000000872a234	main:0x726234	
   0x000000000872a1a0	main:0x7261a0	
   0x0000000008abab00	main:0xab6b00	
   0x000000000f40d188	sdk:0x342188	
   0x000000000f413714	sdk:0x348714	
   0x0000000000000000


00:02:59.199 |I| HLE.GuestThread.49 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000001763a00000
	X[01]:	0x0000001763a00000
	X[02]:	0x00000000089ae4c0 (main:0x9aa4c0)	=> 
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000001763a00000
	X[09]:	0x0000000000000011
	X[10]:	0x0000000000000000
	X[11]:	0x0000000000000000
	X[12]:	0x000000000005d8e8
	X[13]:	0x0000000000000001
	X[14]:	0x0000000000000001
	X[15]:	0x0000000000000000
	X[16]:	0x000000000fd51288
	X[17]:	0x000000000f4155a4 (sdk:0x34a5a4)	=> nn::os::detail::ReaderWriterLockImplByHorizon::ReleaseReadLock(nn::os::ReaderWriterLockType*)
	X[18]:	0x0000000000000039
	X[19]:	0x000000000e5fb670
	X[20]:	0x00000049d878e610 (SP:-0x0060)
	X[21]:	0x0000001763a00000
	X[22]:	0x0000000000000000
	X[23]:	0x0000000000000000
	X[24]:	0xfffffffffffffff0
	X[25]:	0x000000000000003c
	X[26]:	0x000000000e5b3880
	X[27]:	0x000000000000003c
	X[28]:	0x000000000e5fb7f0
	FP:	0x00000049d878e5b0 (SP)
	LR:	0x00000000089a8658 (main:0x9a4658)	=> 
	SP:	0x00000049d878e5b0 (SP)
	PC:	0x00000000089ae4c0 (main:0x9aa4c0)	=> 


00:02:59.199 |E| HLE.GuestThread.49 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000001763BFF000.
00:02:59.248 |E| HLE.GuestThread.49 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 281
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 212
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\ARMeilleure\Translation\Translator.cs:line 155
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 60
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1264
```

### Minimal modpack to reproduce the crash

Three mods that contain assettable. Gave examples above.

**Comment by Raytwo** [comment]
Addressed in v0.23.2
