### ISSUE TITLE
New AssetTable entries inserted at lower line numbers than in the .xml patch.

### ISSUE THREAD

**Issue by ltranc** [Raytwo/Cobalt#22]
### **System Firmware Version**
Ryujinx 1.1.969

### **Atmosphere Version**
Ryujinx

### **Details**
Inserted entries in the AssetTable appear to be inserted at lower line numbers than their location in the AssetTable.xml patch. Causes some minor visual issues with certain lines' changes and additions being overridden. 

### **Examples**
The following 3 examples are taken from [Reverse Recruitment,](https://gamebanana.com/mods/426933) no other mods were loaded.
![vision](https://github.com/Raytwo/Cobalt/assets/84255102/83c883de-09c1-40d5-a63c-d121c7c915c5)
Illusory Doubles (first line) entry nulls all accessories, the following two entries, which were added and inserted, give Illusory Doubles summoned by Corrupted units the Corrupted headwear. Placed underneath the default Illusory Double accessory nulling entry, so that it would add on the helmet after it gets nulled.
![ryujinx_capture_2023-02-25_17-08-07](https://github.com/Raytwo/Cobalt/assets/84255102/09e99d00-0432-4f3c-8a41-09fbf048492e)
This had previously worked.
![ryujinx_capture_2023-08-07_17-19-39](https://github.com/Raytwo/Cobalt/assets/84255102/698ef8b5-f88b-4f66-9560-eb26ea939276)
At some point, AssetTable.xml patching was modified, making it no longer work.

![shield](https://github.com/Raytwo/Cobalt/assets/84255102/92f0355b-bf99-4cc5-b3e1-00c171c9a28e)
The bottom two lines grant Ch17 and Ch19 Marni the Warrior bow animation while wielding Parthia, and null her shield accessory. Placed underneath her default class General entry that assigns the shield, so that it would null the shield.
![ryujinx_capture_2023-04-29_14-52-31](https://github.com/Raytwo/Cobalt/assets/84255102/f8159ece-1ce5-490f-8156-b5820baac0e2)
Previously, nulling the shield had worked.
![ryujinx_capture_2023-08-07_17-22-57](https://github.com/Raytwo/Cobalt/assets/84255102/307c1c52-b2a2-4296-8356-e6d085f467d9)
Placing the entry that nulls the shield at that line no longer works.

![goldmary](https://github.com/Raytwo/Cobalt/assets/84255102/3ac5cf58-7d8b-4f95-a2f4-ed4de69b8a6c)
The third entry is a new line which assigns Goldmary's Hero outfit and scaling to the Sword Fighter class.
![ryujinx_capture_2023-08-07_17-15-08](https://github.com/Raytwo/Cobalt/assets/84255102/8bb1eca4-53b6-4ffc-b8a3-72b03575c5d6)
![ryujinx_capture_2023-08-07_17-15-57](https://github.com/Raytwo/Cobalt/assets/84255102/7f123f0d-4507-420c-aa0f-bbfbbf4a5df0)
A bit crude but, due to being inserted above where it should, the Sword Fighter model uses Goldmary's default VolumeBust value of 1.75, rather than the Hero outfit's value of 2.2.

**Comment by DogeThis** [comment]
Cobalt version is Version 0.22.3 for this issue.

**Comment by DogeThis** [comment]
Fixed in 0.24.0 https://ptb.discord.com/channels/608790115002875934/1129754170208043028/1141103798652244189

**Comment by ltranc** [comment]
https://www.dropbox.com/scl/fi/u4hasepgfzi093q0ndaqd/AssetTable.xml?rlkey=io7c5e3rgkp1rconj0lmdnklh&dl=0
https://www.dropbox.com/scl/fi/rbqi9ofo213j4fvpi4u37/AssetTablePatched.xml?rlkey=j8go64mmirgzqklxlellmk188&dl=0
First link is the AssetTable patch used, second link is the patched AssetTable in engage_patches. It appears that the entry is inserted at the correct line if the line above is edited in some way (or if multiple entries are inserted consecutively, if the line above the first addition is edited).

**Comment by DogeThis** [comment]
Verbal confirmation of fix. https://ptb.discord.com/channels/608790115002875934/1065612171578462278/1148731380193308702
