### ISSUE TITLE
Jumbled item.xml merging

### ISSUE THREAD

**Issue by AugmentedAntics** [Raytwo/Cobalt#23]
Item.xml merging doesn't seem to be working properly, or at least it doesn't seem to be. I have some item mods enabled (such as the one from GameBanana that [adds rings as items that can be carried](https://gamebanana.com/mods/439524)), along with some personal tweak mods that modify other things such as changing flags for existing weapons, changing the price of bento boxes, and adding flier effectiveness on the Croissbow.

However, when these changes are merged, the final item.xml patched into the game has incorrect entries in quite a few places. Depending on the load order, some of the rings from the mod will end up missing, or things such as the Radiant Bow will disappear from the game entirely. When I look at the patched item.xml in the patches folder, I notice that entries are either being overwritten or duplicated over other existing entries, like two copies of the Croissbow appearing with only one of them containing my edit, while it's also overwriting the Radiant Bow entry. Another example is editing the prices of bento boxes in a separate mod, placing that above the rings mod, and allowing Cobalt to merge the two to find the bento edits overwriting ring items. 

Here's a picture of what the Croissbow merge is doing:

![notepad++_UhZ5Rql9KZ](https://github.com/Raytwo/Cobalt/assets/54159324/bd25e861-efdd-43e1-b223-77a2af031353)

The Radiant Bow (Light Bow in the game's files) is supposed to be the one below the Killer Bow.

It seems this will be a lot more likely to happen if a mod contains a lot of item edits, and it's being merged with other mods that either add or edit other items.

**Comment by DogeThis** [comment]
@AugmentedAntics please include a zip of your engage/mod folder where this issue can be reproduced.

**Comment by AugmentedAntics** [comment]
[https://www.dropbox.com/scl/fi/c88fxguh5ia56cb91r9qc/mods.zip?rlkey=zmi7p5m4s2a222ckq2h0j1x10&dl=0](https://www.dropbox.com/scl/fi/c88fxguh5ia56cb91r9qc/mods.zip?rlkey=zmi7p5m4s2a222ckq2h0j1x10&dl=0)

The edit is in the "Cobalt Randomizer Mod - Items" folder.

**Comment by chrom-sevy** [comment]
as of Cobalt v0.29 the xml file looks like this:
![image](https://github.com/Raytwo/Cobalt/assets/82708310/77f0f682-079c-4ea4-a7f1-ac6aae472996)

is this correct?

Also for some reason your mod folder crashes the game for me both in v0.28 v0.29. There are a lot of mods in there, so beats me.

**Comment by DogeThis** [comment]
@AugmentedAntics ^^

**Comment by AugmentedAntics** [comment]
Well, mine didn't look like that until I moved mod orders around again (by putting mods that added things above mods that just edited things). And unless you have the skill expansion patch installed, your game my crash, since this setup uses a mod that adds a bunch of new skills.

**Comment by Raytwo** [comment]
Well, changes have been made so please try it and report back, hopefully it works now
