### ISSUE TITLE
Version 0.26.0 - Forgot to disable the menu?

### ISSUE THREAD

**Issue by pandavova** [Raytwo/Cobalt#24]
Just FYI, I don't know if this fits here or has something to do with the mods I installed but I got saw this message (Ryujinx 1.1.1000):
![Ryujinx_26 08 2023_00-03-44](https://github.com/Raytwo/Cobalt/assets/9296158/863a29e5-75a4-42a2-b55d-338a0abd30fe)

**Comment by Raytwo** [comment]
No, it's now an official feature, although a bit empty. Thanks for reporting though!

**Comment by pandavova** [comment]
Ehm looks like I did something wrong and the message doesn't appear anymore. I think I was on an older Cobalt version and upgraded by drag and drop which didn't apply I think..? 
I know deleted everything Cobalt related and now it doesn't show up, sorry I guess.
As an Idea, would it be possible to include both version numbers (base game + cobalt) to the menus after the titlescreen? Would maybe catch someone like me.

Anyway, now with Cobalt 0.26.1 and Battle Outfits 2.3.5, everything works as expected. (Cobalt 0.26.0 crashed as you prolly know.)
