### ISSUE TITLE
Cobalt Panics after using update feature

### ISSUE THREAD

**Issue by PointBlankVT** [Raytwo/Cobalt#27]
![IMG_0038](https://github.com/Raytwo/Cobalt/assets/144175659/126336b5-567a-4c7e-bb5f-bd5a63a9c030)

After updating Cobalt using the ingame update prompt, I am no longer able to launch the game. I have tried reinstalling Cobalt, but it does not fix the issue.

**Comment by DogeThis** [comment]
Could you provide the mods you are using as a zip file?

**Comment by PointBlankVT** [comment]
> Could you provide the mods you are using as a zip file?

The zipped file won't fit in a comment, so I've uploaded the zip to google drive; if this isn't allowed or recommended, I'm sorry, I've never used github before.

https://drive.google.com/file/d/1nCEAZmQ8aZDjbTS4EISCqwTtpcTJSBuL/view?usp=drive_link

**Comment by DogeThis** [comment]
> > Could you provide the mods you are using as a zip file?
> 
> The zipped file won't fit in a comment, so I've uploaded the zip to google drive; if this isn't allowed or recommended, I'm sorry, I've never used github before.
> 
> https://drive.google.com/file/d/1nCEAZmQ8aZDjbTS4EISCqwTtpcTJSBuL/view?usp=drive_link

This is fine, but your file is private.

**Comment by PointBlankVT** [comment]
> > > Could you provide the mods you are using as a zip file?
> > 
> > 
> > The zipped file won't fit in a comment, so I've uploaded the zip to google drive; if this isn't allowed or recommended, I'm sorry, I've never used github before.
> > https://drive.google.com/file/d/1nCEAZmQ8aZDjbTS4EISCqwTtpcTJSBuL/view?usp=drive_link
> 
> This is fine, but your file is private, you need to share it with all viewers.

Shoot, sorry. Access should be granted now.

https://drive.google.com/file/d/1nCEAZmQ8aZDjbTS4EISCqwTtpcTJSBuL/view?usp=sharing

**Comment by chrom-sevy** [comment]
One initial problem spotted was the incorrect display of a character example (job xml). Thane98's Astra encountered the same problem, solution should be found relatively soon.

**Comment by chrom-sevy** [comment]
Should be fixed as of 0.29.1

**Comment by DogeThis** [comment]
@PointBlankVT ^^

**Comment by PointBlankVT** [comment]
Thank you, all my mods are working now!
