### ISSUE TITLE
Cobal Panic

### ISSUE THREAD

**Issue by sdong1996** [Raytwo/Cobalt#29]
System Firmware: 16.1.0
Atmosphere: 1.5.5

Error:
Cobalt v0.30.2 has panicked at 'C:\Users\Raytwo\.cargo\git\checkouts\cobalt_xml_merge-cc3fc4d765ad162f\30a72b4\src\params.rs:55:13' with the following message:
failed to parse line: invalid comment at 1:1 cause expected '-->' at 1:21

What I did: start fe enagage w/ cobalt + mods. (works fine on my ryujinx emulator)

**Comment by DogeThis** [comment]
Can you include a zip of your mod folder?

**Comment by sdong1996** [comment]
zip is attached. it's too big so I split them into parts
[z - Fire Emblem Erngage.zip](https://github.com/Raytwo/Cobalt/files/12743107/z.-.Fire.Emblem.Erngage.zip)
[new_game_1.zip](https:/
[Emblem Classes and More 4.1.zip](https://github.com/Raytwo/Cobalt/files/12743110/Emblem.Classes.and.More.4.1.zip)
/gi
[new_game.zip](https://github.com/Raytwo/Cobalt/files/12743109/new_game.zip)
thub.com/Raytwo/Cobalt/files/12743108/new_game_1.zip)

**Comment by sdong1996** [comment]
[new_game_1.zip](https://github.com/Raytwo/Cobalt/files/12743114/new_game_1.zip)

**Comment by sdong1996** [comment]
The last mod was baomo, which was too big

**Comment by sdong1996** [comment]
so a total of 4 zips (excluding baomo). sorry for the mess

**Comment by sdong1996** [comment]
also on my OLED switch if that helps. I know that tegraexplorer doesn't work for me on my oled switch

**Comment by chrom-sevy** [comment]
Can you send the logs too @sdong1996

**Comment by chrom-sevy** [comment]
I identified the problem, should be in new_game_1 assettable. Can make a quick fix for this quite soon.

**Comment by sdong1996** [comment]
hey! thanks for getting back to me so quick and w/ a solution to boot!

**Comment by DogeThis** [comment]
Hello, try using the newly release 0.31 for now.
