### ISSUE TITLE
Issue at opening

### ISSUE THREAD

**Issue by AvalonS12** [Raytwo/Cobalt#3]
Hello! I encountered this issue
![image](https://github.com/Raytwo/Cobalt/assets/136358785/cfcc25fb-8e22-49ea-9d53-c3081267bb37)

**Comment by AvalonS12** [comment]
[BondRingItems_Wave5.zip](https://github.com/Raytwo/Cobalt/files/11725640/BondRingItems_Wave5.zip)
[Gold Crystals and Banes.zip](https://github.com/Raytwo/Cobalt/files/11725642/Gold.Crystals.and.Banes.zip)
[Skill Expansion.zip](https://github.com/Raytwo/Cobalt/files/11725644/Skill.Expansion.zip)

These are the mods i added, as well as the Battle Outfits mod

**Comment by Raytwo** [comment]
Hey there, I recently found out that toggling didn't work until version 0.7.2, so that was my bad.
The latest version of Cobalt also provided better error messages for XML patching, so please update and report back if you do not find the issue.

**Comment by AvalonS12** [comment]
hello! thanks for replying, i updated to the 8.0 version and tried to add back the mod, but i still got the same error as in the screenshot above, with the exception of  "/skill.rs:215:4". I tried to add the other mods one at a time, and it seems only mods that "combine" skill files will cause problems

**Comment by Raytwo** [comment]
Judging by the place where it is crashing, it seems either:
- One of your patch files is editing the very last entry in the original XML which prevents the patching from happening
- You have a skill.xml.bundle in one of your mods which causes conflicts

**Comment by AvalonS12** [comment]
Hmm i do see a "skills.byte.bundle" and a "skill.bundle", will removing the bundle file break the mod?
