### ISSUE TITLE
[Panic] keeps crashing

### ISSUE THREAD

**Issue by Jacolite** [Raytwo/Cobalt#30]
### System Firmware Version

16.0.3

### Atmosphere Version

N/A

### Cobalt Version

0.30.2

### Steps to reproduce

I installed cobalt 
then tried to use bomo by itself

### Details

I finally got cobalt to work and show up on the title screen but i cannot go past prologue as it keeps crashing upon the cutscene ending
![Screenshot 2023-09-28 021019](https://github.com/Raytwo/Cobalt/assets/146311835/30a031cc-873f-445c-b870-329bdf090c0e)
[](url)
![Screenshot 2023-09-28 021233](https://github.com/Raytwo/Cobalt/assets/146311835/81d4d981-6617-42ad-b70d-9a93cd221b16)
all the mods here^

**Comment by DogeThis** [comment]
Please rollback to 29.3 as we investigate this issue.
https://github.com/Raytwo/Cobalt/releases/tag/v0.29.3

**Comment by Jacolite** [comment]
ok so i tried again but instead of it giving me the error it just crashes at the start of hub 
[Ryujinx_1.1.1037_2023-09-29_14-17-37.log](https://github.com/Raytwo/Cobalt/files/12770187/Ryujinx_1.1.1037_2023-09-29_14-17-37.log)

**Comment by Raytwo** [comment]
Hey there, we're aware of this, until this gets addressed please update to v0.31.0
