### ISSUE TITLE
[Crash] Updating crashes Engage on Title screen.

### ISSUE THREAD

**Issue by kratoscar2000** [Raytwo/Cobalt#36]
### System Firmware Version

16.0.3

### Atmosphere Version

1.5.3

### Cobalt Version

0.25.01

### Can the crash be consistently reproduced?

Yes

### At what moment does the crash happen?

- [ ] Before the Switch boot animation
- [ ] After the Switch boot animation
- [X] While the picture is displayed on boot
- [ ] While the spinner is displayed on boot
- [ ] At random
- [ ] After a long time playing

### Details

I am trying to update my Cobalt as my current version doesnt displays the Cobalt options on the menu.
I tried by just replacing the files on my current version but that crashes the game as soon as I hit the title screen.
I dont want to use the updater as I fear Ninty will block my console as soon as I enable it.
I paid someone to hack my switch so I am not sure about a bunch of stuff. Any help will be appreciated.

### Crash report

```shell
Atmosphère Crash Report (v1.7):
Result:                          0x4A8 (2168-0002)

Process Info:
    Process Name:                Application
    Program ID:                  0100a6301214e000
    Process ID:                  000000000000032a
    Process Flags:               00001877
    User Exception Address:      00000052747da000
Exception Info:
    Type:                        Data Abort
    Address:                     0000000000000018
    Fault Address:               0000000000000000
Crashed Thread Info:
    Thread ID:                   000000000002c74b
    Thread Name:                 MainThread
    Stack Region:                000000607663f000-000000607673f000
    Registers:
        X[00]:                   000000690183c270
        X[01]:                   ffffffffffffffff
        X[02]:                   3e6553d5dd004e25
        X[03]:                   00000069a5d96140
        X[04]:                   0000000000000000
        X[05]:                   000000363f6c20d0 (SwitchPlayer.nss + 0x3cbe0d0)
        X[06]:                   0000000000000000
        X[07]:                   000000607673e23c
        X[08]:                   00000069a5b3ee70
```

### Minimal modpack to reproduce the crash

I have the battle outfits, playable bosses, emblem and classes and custom outfits (The ones ported from say FF7R) mods.

**Comment by DogeThis** [comment]
The crash log is incomplete.

But the first thing you could try is, uninstalling all your mods and seeing if you can boot Engage.
