### ISSUE TITLE
[Panic] Cobalt v0.35.2 has panicked at 'crates\cobalt\src\catalog.rs:20:58' with the following message:

### ISSUE THREAD

**Issue by Elesion12** [Raytwo/Cobalt#37]
### System Firmware Version

13.2.1

### Atmosphere Version

skip

### Cobalt Version

Cobalt v0.35.2

### Steps to reproduce

Every time I try to load the game on Ryyujinx, a bit after after having loaded the shader cache, the error suddenly pops up
and displays the details I have screenshoted.

### Details

![image](https://github.com/Raytwo/Cobalt/assets/149794630/e1774b06-06e7-4147-b165-590e7b658171)

**Comment by Raytwo** [comment]
Install properly.
