### ISSUE TITLE
[Panic] Game crashing with install of cobalt

### ISSUE THREAD

**Issue by greenflare27** [Raytwo/Cobalt#39]
### System Firmware Version

16.0.2

### Atmosphere Version

Emulator

### Cobalt Version

v0.36.0

### Steps to reproduce

Installed Cobalt to Ryujinx using the Installation processes listed
![image](https://github.com/Raytwo/Cobalt/assets/106407071/7951eee4-82d6-425e-a625-f98fb78bcf0a)
![image](https://github.com/Raytwo/Cobalt/assets/106407071/65d16c4b-91fd-4c88-84d4-17a0b0971aa2)
with the mods folder empty of any mods.

### Details

![image](https://github.com/Raytwo/Cobalt/assets/106407071/041c7400-da0b-405a-ba26-02d302396292)

### Minimal modpack to reproduce the panic

Not modded

**Comment by Raytwo** [comment]
Fixed with Cobalt v0.36.1
