### ISSUE TITLE
Chapter.xml merging issue

### ISSUE THREAD

**Issue by DogeThis** [Raytwo/Cobalt#4]
Cobalt version - latest at the time of filing (0.9.2)

Two mods are involved with this issue.
1. `no enemy phase music` - Modifies the `EnemyPhaseBgm`, `AllyPhaseBgm`, and `EnemyEncountBgm`, attributes in Data -> Param
In isolation, this makes it so that the player phase music and the enemy phase music are the same, removing the music transition between player and enemy phases.
2. `emblems dont kill` - Modifies the `Flag` attribute in Data -> Param. In isolation, this makes it so that, during emblem paralogues only, killed allies in Classic mode do not die and merely retreat.

Steps to reproduce:
1. Load the two mods attached into the mod folder <img width="232" alt="image" src="https://github.com/Raytwo/Cobalt/assets/3914917/35e08993-dab6-452e-8ff0-b80cde92f19f">
2. In classic mode, enter an emblem paralogue.
3. Start the battle.
4. Purposely position a weak ally in the line of fire (such that they will die)
5. Finish turn and start enemy turn.

Expected:
The enemy phase music doesn't play and the paralogue-specific music continues to play. 
Weak character gets killed but doesn't die.

Actual:
While weak character gets killed but doesn't die, the enemy phase music plays instead of the paralogue-specific music.

Hypothesis:
Naive guess is, perhaps merging needs to be done per parameter, and not by line.

[for repro.zip](https://github.com/Raytwo/Cobalt/files/11790465/for.repro.zip)

**Comment by DogeThis** [comment]
[FirstSlotShouldBeParalogue.zip](https://github.com/Raytwo/Cobalt/files/11960258/FirstSlotShouldBeParalogue.zip)

Not quite sure how save files like to be passed in this game, so here's all my saves. The first slot save should be Ike's paralogue and I have a weak unit fielded :).

**Comment by DogeThis** [comment]
Shoot, I forgot that Vander can't die. Please field another unit in case you get to this before I fix that save.

**Comment by DogeThis** [comment]
[FirstSlotShouldBeParalogue2.zip.zip](https://github.com/Raytwo/Cobalt/files/11965142/FirstSlotShouldBeParalogue2.zip.zip)

**Comment by DogeThis** [comment]
Here's `Chapter#0` (application of the `no enemy phase music` mod)
followed by `Chapter#1) (application of `the emblems dont kill` mod)

[Chapter Merges.zip](https://github.com/Raytwo/Cobalt/files/11998162/Chapter.Merges.zip)

Displaying as pretty XML in WinMerge shows
<img width="1865" alt="image" src="https://github.com/Raytwo/Cobalt/assets/3914917/e7beb004-0d04-404d-ba53-44e38c287671">

We lose the changes to `EnemyEncountBgm`, `EnemyPhaseBgm`, in #1, which applies the `Flag` change.

**Comment by Raytwo** [comment]
Fixed, thanks for the report.
