### ISSUE TITLE
[Panic] Brief description of the issue

### ISSUE THREAD

**Issue by Nayjel9** [Raytwo/Cobalt#41]
### System Firmware Version

16.1.0

### Atmosphere Version

Ryujinx

### Cobalt Version

1.0.0

### Steps to reproduce

So I tried to install the Cobalt. Made a folder labeled "skyline" and placed the files in there. Once I booted the game, this happened.

### Details

![image_2023-12-01_163050269](https://github.com/Raytwo/Cobalt/assets/105796408/7b084de8-b59e-4b0f-8f5d-beac67e27888)

**Comment by Raytwo** [comment]
https://github.com/Raytwo/Cobalt/wiki/Debugging-your-modpack#my-game-is-updated-to-200-but-i-immediately-crash-on-boot
