### ISSUE TITLE
Units repeated in Inherit Skills list

### ISSUE THREAD

**Issue by sophxm** [Raytwo/Cobalt#51]
### System Firmware Version

18.1.0

### Atmosphere Version

N/A

### Cobalt Version

1.14.0

### Steps to reproduce

1) Open the Inherit Skills menu (either via the Arena, or Start -> Somniel -> Inherit Skills)
2) The list of units repeats once:

![Duplicate entries in inherit skills](https://github.com/user-attachments/assets/0c4e1984-3623-4f31-afb8-60f2c86415f8)

### Details

Doesn't cause a panic/crash and there isn't an issue template for "other bug", but it occurs on an unmodded save so it seems like a Cobalt issue.

**Comment by Raytwo** [comment]
Addressed in v1.15.1, thanks for reporting
