### ISSUE TITLE
Missing Unity shaders for the model guide

### ISSUE THREAD

**Issue by FPSeph** [Raytwo/Cobalt#7]
Hello, I was checking your cobalt wiki about how to create a custom bundle for FEEngage, really nice stuff.

However I'm stuck in the shader part, the picture uses a shader called CharaStandard which it also claims thar we can get it from you, question, where can I find this particular shader?

**Comment by Raytwo** [comment]
Hello, yes the guide still need some polish, until then, here's a [link to the shaders](https://cdn.discordapp.com/attachments/1065612171578462278/1123685325475164171/EngageShaders.unitypackage).

Make sure to make them addressable (``CustomRP/Shaders/Chara/CharaHair.shader`` etc) when using them.

**Comment by DogeThis** [comment]
I've added the shader to the guide.

**Comment by FPSeph** [comment]
I'm talking about the archive and their ID's that appeared in the original file, the original had 7 archive dependencies alongside the CAB while the modded file only has the CAB.

This is the modded file:
![Captura de Tela (27)](https://github.com/Raytwo/Cobalt/assets/138726163/1516a1e0-8a7a-40cb-b2e1-80e088bfcf51)

And this is the original one:
![Captura de Tela (28)](https://github.com/Raytwo/Cobalt/assets/138726163/9fa99470-2412-4c75-b57f-b4dd27d95afb)

Is this how it's supposed to be or am I doing something wrong?
Also, is there a tutorial on how to use CBT to create a new file for the game?

**Comment by Raytwo** [comment]
Your bundle should only have shaders as dependencies, so if you depends on fallbackerror this should be fine, yes.
As for CBT, I did not write a tutorial for it but I believe there are a few around

**Comment by FPSeph** [comment]
Ah OK, thanks again.

**Comment by Raytwo** [comment]
For whoever stumbles upon this, here's a guide: [https://github.com/Raytwo/Cobalt/wiki/Reproducing-a-shader-from-the-game](https://github.com/Raytwo/Cobalt/wiki/Reproducing-a-shader-from-the-game)
