### ISSUE TITLE
remaining missing item.xml support

### ISSUE THREAD

**Issue by ErinRose0** [Raytwo/Cobalt#8]
錬成素材交換, 相性, 報酬, エンゲージ武器強化 (reforge material exchange, weapon triangle, item rewards, and engage weapon gem forge tables) sheets not yet supported but edited in my project (latter two are very common to edit)

(sorry raytwo)

[erngage release.zip](https://github.com/Raytwo/Cobalt/files/11974472/erngage.release.zip)

**Comment by Raytwo** [comment]
Pain.
