### ISSUE TITLE
Emulator Crash

### ISSUE THREAD

**Issue by mbmcake** [Raytwo/Cobalt#9]
Ryujinx crashes when trying to open the game. With no Cobalt, the game runs fine, it just happens when cobalt is installed, any way to fix this?
![imagen_2023-07-10_144947751](https://github.com/Raytwo/Cobalt/assets/75872627/5813e054-f97e-4c01-acea-7eabeb742b6a)

**Comment by Raytwo** [comment]
We'll need more informations than that to help you.
Please send the latest .log file from Ryujinx right after a crash, and eventually what's shown in the Ryujinx console too.

**Comment by mbmcake** [comment]
[Ryujinx_1.1.956_2023-07-10_15-04-08.log](https://github.com/Raytwo/Cobalt/files/12006196/Ryujinx_1.1.956_2023-07-10_15-04-08.log)

**Comment by Raytwo** [comment]
Sorry but there's just nothing of value in there, can't help with that.

**Comment by mbmcake** [comment]
What should I send then?

**Comment by Raytwo** [comment]
Nevermind, update your game, you're on 1.3.0.
